# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.srcs/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0.xci
# IP: The module: 'soc_core_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.gen/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_core_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.gen/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_core_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.srcs/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0.xci
# IP: The module: 'soc_core_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.gen/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_core_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.gen/sources_1/bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_core_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
