@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< Updated upstream:Gateware_Xilinx_Zynq/fpga project/fpga project.sim/sim_1/behav/xsim/elaborate.bat
REM Generated by Vivado on Sun May 31 09:20:27 +0200 2026
=======
REM Generated by Vivado on Wed Apr 08 19:38:38 +0200 2026
>>>>>>> Stashed changes:Gateware/fpga project/fpga project.sim/sim_1/behav/xsim/elaborate.bat
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM elaborate design
<<<<<<< Updated upstream:Gateware_Xilinx_Zynq/fpga project/fpga project.sim/sim_1/behav/xsim/elaborate.bat
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_hub75_bram_behav xil_defaultlib.tb_hub75_bram -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_hub75_bram_behav xil_defaultlib.tb_hub75_bram -log elaborate.log
=======
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot clockdivider_2out_TB_behav xil_defaultlib.clockdivider_2out_TB -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot clockdivider_2out_TB_behav xil_defaultlib.clockdivider_2out_TB -log elaborate.log
>>>>>>> Stashed changes:Gateware/fpga project/fpga project.sim/sim_1/behav/xsim/elaborate.bat
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
