# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraint.xdc

# Block Designs: bd/soc_core/soc_core.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core || ORIG_REF_NAME==soc_core} -quiet] -quiet

# IP: bd/soc_core/ip/soc_core_smartconnect_0_0/soc_core_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core_smartconnect_0_0 || ORIG_REF_NAME==soc_core_smartconnect_0_0} -quiet] -quiet

# IP: bd/soc_core/ip/soc_core_processing_system7_0_1/soc_core_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core_processing_system7_0_1 || ORIG_REF_NAME==soc_core_processing_system7_0_1} -quiet] -quiet

# IP: bd/soc_core/ip/soc_core_axi_bram_ctrl_0_0/soc_core_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core_axi_bram_ctrl_0_0 || ORIG_REF_NAME==soc_core_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/soc_core/ip/soc_core_axi_bram_ctrl_0_bram_0/soc_core_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==soc_core_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/soc_core/ip/soc_core_rst_ps7_0_50M_0/soc_core_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_core_rst_ps7_0_50M_0 || ORIG_REF_NAME==soc_core_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/Users/bende/Documents/GitHub/FPGA-project/Gateware/fpga project/fpga project.gen/sources_1/bd/soc_core/soc_core_ooc.xdc
