@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< Updated upstream:Gateware_Xilinx_Zynq/fpga project/fpga project.sim/sim_1/behav/xsim/compile.bat
REM Generated by Vivado on Sun May 31 09:20:25 +0200 2026
=======
REM Generated by Vivado on Wed Apr 08 19:38:34 +0200 2026
>>>>>>> Stashed changes:Gateware/fpga project/fpga project.sim/sim_1/behav/xsim/compile.bat
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

REM compile VHDL design sources
echo "xvhdl --incr --relax -prj tb_hub75_bram_vhdl.prj"
call xvhdl  --incr --relax -prj tb_hub75_bram_vhdl.prj -log xvhdl.log
call type xvhdl.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
